site_name: Antonin Poch√©
site_url: https://antoninpoche.github.io/

nav:
  - Intro: index.md
  - Research: /#research
  - News: /#news
  - Publications: /#publications
  - Software: /#software
  - Talks: /#talks
  - Teaching: /#teaching

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky

extra_css:
  - stylesheets/extra.css
